playsfor(avery_bradley,boston_celtics).
playsfor(jaylen_brown,boston_celtics).
playsfor(jae_crowder,boston_celtics).
playsfor(gerald_green,boston_celtics).
playsfor(al_horford,boston_celtics).
playsfor(demetrius_jackson,boston_celtics).
playsfor(jonas_jerebko,boston_celtics).
playsfor(amir_johnson,boston_celtics).
playsfor(jordan_mickey,boston_celtics).
playsfor(kelly_olynyk,boston_celtics).
playsfor(terry_rozier,boston_celtics).
playsfor(marcus_smart,boston_celtics).
playsfor(isaiah_thomas,boston_celtics).
playsfor(james_young,boston_celtics).
playsfor(tyler_zeller,boston_celtics).
playsfor(anthony_bennett,brooklyn_nets).
playsfor(bojan_bogdanovic,brooklyn_nets).
playsfor(trevor_booker,brooklyn_nets).
playsfor(yogi_ferrell,brooklyn_nets).
playsfor(randy_foye,brooklyn_nets).
playsfor(justin_hamilton,brooklyn_nets).
playsfor(joe_harris,brooklyn_nets).
playsfor(rondae_hollis-jefferson,brooklyn_nets).
playsfor(sean_kilpatrick,brooklyn_nets).
playsfor(caris_leVert,brooklyn_nets).
playsfor(jeremy_lin,brooklyn_nets).
playsfor(brook_lopez,brooklyn_nets).
playsfor(chris_mccullough,brooklyn_nets).
playsfor(luis_scola,brooklyn_nets).
playsfor(isaiah_whitehead,brooklyn_nets).
playsfor(carmelo_anthony,new_york_knicks).
playsfor(ron_baker,new_york_knicks).
playsfor(willy_hernangomez,new_york_knicks).
playsfor(justin_holiday,new_york_knicks).
playsfor(brandon_jennings,new_york_knicks).
playsfor(mindaugas_kuzminskas,new_york_knicks).
playsfor(courtney_lee,new_york_knicks).
playsfor(maurice_ndour,new_york_knicks).
playsfor(joakim_noah,new_york_knicks).
playsfor(kyle_o_quinn,new_york_knicks).
playsfor(marshall_plumlee,new_york_knicks).
playsfor(kristaps_porzingis,new_york_knicks).
playsfor(derrick_rose,new_york_knicks).
playsfor(lance_thomas,new_york_knicks).
playsfor(sasha_Vujacic,new_york_knicks).
playsfor(jerryd_bayless,philadelphia_76ers).
playsfor(robert_covington,philadelphia_76ers).
playsfor(joel_embiid,philadelphia_76ers).
playsfor(gerald_henderson,philadelphia_76ers).
playsfor(richaun_holmes,philadelphia_76ers).
playsfor(ersan_ilyasova,philadelphia_76ers).
playsfor(timothe_luwawu-cabarrot,philadelphia_76ers).
playsfor(tjmcconnell,philadelphia_76ers).
playsfor(nerlens_noel,philadelphia_76ers).
playsfor(jahlil_okafor,philadelphia_76ers).
playsfor(sergio_rodriguez,philadelphia_76ers).
playsfor(dario_saric,philadelphia_76ers).
playsfor(ben_simmons,philadelphia_76ers).
playsfor(nik_stauskas,philadelphia_76ers).
playsfor(hollis_thompson,philadelphia_76ers).
playsfor(bruno_caboclo,toronto_raptors).
playsfor(demarre_carroll,toronto_raptors).
playsfor(demar_derozan,toronto_raptors).
playsfor(cory_joseph,toronto_raptors).
playsfor(kyle_lowry,toronto_raptors).
playsfor(lucas_nogueira,toronto_raptors).
playsfor(patrick_patterson,toronto_raptors).
playsfor(jakob_poltl,toronto_raptors).
playsfor(norman_powell,toronto_raptors).
playsfor(terrence_ross,toronto_raptors).
playsfor(pascal_siakam,toronto_raptors).
playsfor(jared_sullinger,toronto_raptors).
playsfor(jonas_Valanciunas,toronto_raptors).
playsfor(fred_VanVleet,toronto_raptors).
playsfor(delon_wright,toronto_raptors).
playsfor(jimmy_butler,chicago_bulls).
playsfor(isaiah_canaan,chicago_bulls).
playsfor(michael_carter-williams,chicago_bulls).
playsfor(cristiano_felicio,chicago_bulls).
playsfor(taj_gibson,chicago_bulls).
playsfor(jerian_grant,chicago_bulls).
playsfor(rjhunter,chicago_bulls).
playsfor(robin_lopez,chicago_bulls).
playsfor(doug_mcdermott,chicago_bulls).
playsfor(nikola_mirotic,chicago_bulls).
playsfor(bobby_portis,chicago_bulls).
playsfor(rajon_rondo,chicago_bulls).
playsfor(denzel_Valentine,chicago_bulls).
playsfor(dwyane_wade,chicago_bulls).
playsfor(paul_zipser,chicago_bulls).
playsfor(chris_andersen,cleveland_cavaliers).
playsfor(mike_dunleavy,cleveland_cavaliers).
playsfor(kay_felder,cleveland_cavaliers).
playsfor(channing_frye,cleveland_cavaliers).
playsfor(kyrie_irving,cleveland_cavaliers).
playsfor(lebron_james,cleveland_cavaliers).
playsfor(richard_jefferson,cleveland_cavaliers).
playsfor(james_jones,cleveland_cavaliers).
playsfor(deandre_liggins,cleveland_cavaliers).
playsfor(kevin_love,cleveland_cavaliers).
playsfor(jordan_mcrae,cleveland_cavaliers).
playsfor(iman_shumpert,cleveland_cavaliers).
playsfor(jrsmith,cleveland_cavaliers).
playsfor(tristan_thompson,cleveland_cavaliers).
playsfor(mo_williams,cleveland_cavaliers).
playsfor(aron_baynes,detroit_pistons).
playsfor(reggie_bullock,detroit_pistons).
playsfor(kentavious_caldwell-pope,detroit_pistons).
playsfor(andre_drummond,detroit_pistons).
playsfor(henry_ellenson,detroit_pistons).
playsfor(michael_gbinije,detroit_pistons).
playsfor(tobias_harris,detroit_pistons).
playsfor(darrun_hilliard,detroit_pistons).
playsfor(reggie_jackson,detroit_pistons).
playsfor(stanley_johnson,detroit_pistons).
playsfor(jon_leuer,detroit_pistons).
playsfor(boban_marjanovic,detroit_pistons).
playsfor(marcus_morris,detroit_pistons).
playsfor(ish_smith,detroit_pistons).
playsfor(beno_udrih,detroit_pistons).
playsfor(lavoy_allen,indiana_pacers).
playsfor(aaron_brooks,indiana_pacers).
playsfor(rakeem_christmas,indiana_pacers).
playsfor(monta_ellis,indiana_pacers).
playsfor(paul_george,indiana_pacers).
playsfor(al_jefferson,indiana_pacers).
playsfor(cjmiles,indiana_pacers).
playsfor(georges_niang,indiana_pacers).
playsfor(glenn_robinson,indiana_pacers).
playsfor(kevin_seraphin,indiana_pacers).
playsfor(rodney_stuckey,indiana_pacers).
playsfor(jeff_teague,indiana_pacers).
playsfor(myles_turner,indiana_pacers).
playsfor(joseph_young,indiana_pacers).
playsfor(thaddeus_young,indiana_pacers).
playsfor(giannis_antetokounmpo,milwaukee_bucks).
playsfor(michael_beasley,milwaukee_bucks).
playsfor(malcolm_brogdon,milwaukee_bucks).
playsfor(matthew_dellavedova,milwaukee_bucks).
playsfor(john_henson,milwaukee_bucks).
playsfor(thon_maker,milwaukee_bucks).
playsfor(khris_middleton,milwaukee_bucks).
playsfor(greg_monroe,milwaukee_bucks).
playsfor(steve_novak,milwaukee_bucks).
playsfor(jabari_parker,milwaukee_bucks).
playsfor(miles_plumlee,milwaukee_bucks).
playsfor(tony_snell,milwaukee_bucks).
playsfor(mirza_teletovic,milwaukee_bucks).
playsfor(jason_terry,milwaukee_bucks).
playsfor(rashad_Vaughn,milwaukee_bucks).
playsfor(kent_bazemore,atlanta_hawks).
playsfor(deandre_bembry,atlanta_hawks).
playsfor(malcolm_delaney,atlanta_hawks).
playsfor(tim_hardaway,atlanta_hawks).
playsfor(dwight_howard,atlanta_hawks).
playsfor(kris_humphries,atlanta_hawks).
playsfor(ryan_kelly,atlanta_hawks).
playsfor(kyle_korver,atlanta_hawks).
playsfor(paul_millsap,atlanta_hawks).
playsfor(mike_muscala,atlanta_hawks).
playsfor(taurean_prince,atlanta_hawks).
playsfor(dennis_schroder,atlanta_hawks).
playsfor(mike_scott,atlanta_hawks).
playsfor(thabo_sefolosha,atlanta_hawks).
playsfor(tiago_splitter,atlanta_hawks).
playsfor(nicolas_batum,charlotte_hornets).
playsfor(marco_belinelli,charlotte_hornets).
playsfor(treveon_graham,charlotte_hornets).
playsfor(aaron_harrison,charlotte_hornets).
playsfor(spencer_hawes,charlotte_hornets).
playsfor(roy_hibbert,charlotte_hornets).
playsfor(frank_kaminsky,charlotte_hornets).
playsfor(michael_kidd-gilchrist,charlotte_hornets).
playsfor(jeremy_lamb,charlotte_hornets).
playsfor(brian_roberts,charlotte_hornets).
playsfor(ramon_sessions,charlotte_hornets).
playsfor(kemba_walker,charlotte_hornets).
playsfor(marvin_williams,charlotte_hornets).
playsfor(christian_wood,charlotte_hornets).
playsfor(cody_zeller,charlotte_hornets).
playsfor(luke_babbitt,miami_heat).
playsfor(chris_bosh,miami_heat).
playsfor(goran_dragic,miami_heat).
playsfor(wayne_ellington,miami_heat).
playsfor(udonis_haslem,miami_heat).
playsfor(james_johnson,miami_heat).
playsfor(tyler_johnson,miami_heat).
playsfor(rodney_mcgruder,miami_heat).
playsfor(josh_mcroberts,miami_heat).
playsfor(willie_reed,miami_heat).
playsfor(josh_richardson,miami_heat).
playsfor(dion_waiters,miami_heat).
playsfor(hassan_whiteside,miami_heat).
playsfor(derrick_williams,miami_heat).
playsfor(justise_winslow,miami_heat).
playsfor(djaugustin,orlando_magic).
playsfor(bismack_biyombo,orlando_magic).
playsfor(evan_fournier,orlando_magic).
playsfor(aaron_gordon,orlando_magic).
playsfor(jeff_green,orlando_magic).
playsfor(mario_hezonja,orlando_magic).
playsfor(serge_ibaka,orlando_magic).
playsfor(jodie_meeks,orlando_magic).
playsfor(arinze_onuaku,orlando_magic).
playsfor(elfrid_payton,orlando_magic).
playsfor(damjan_rudez,orlando_magic).
playsfor(nikola_Vucevic,orlando_magic).
playsfor(cjwatson,orlando_magic).
playsfor(cjwilcox,orlando_magic).
playsfor(stephen_zimmerman,orlando_magic).
playsfor(bradley_beal,washington_wizards).
playsfor(trey_burke,washington_wizards).
playsfor(marcin_gortat,washington_wizards).
playsfor(danuel_house,washington_wizards).
playsfor(ian_mahinmi,washington_wizards).
playsfor(sheldon_mcclellan,washington_wizards).
playsfor(markieff_morris,washington_wizards).
playsfor(andrew_nicholson,washington_wizards).
playsfor(daniel_ochefu,washington_wizards).
playsfor(kelly_oubre,washington_wizards).
playsfor(otto_porter,washington_wizards).
playsfor(tomas_satoransky,washington_wizards).
playsfor(jason_smith,washington_wizards).
playsfor(marcus_thornton,washington_wizards).
playsfor(john_wall,washington_wizards).
playsfor(justin_anderson,dallas_mavericks).
playsfor(jose_juan_barea,dallas_mavericks).
playsfor(harrison_barnes,dallas_mavericks).
playsfor(andrew_bogut,dallas_mavericks).
playsfor(nicolas_brussino,dallas_mavericks).
playsfor(seth_curry,dallas_mavericks).
playsfor(dorian_finney-smith,dallas_mavericks).
playsfor(jonathan_gibson,dallas_mavericks).
playsfor(ajhammons,dallas_mavericks).
playsfor(devin_harris,dallas_mavericks).
playsfor(wesley_matthews,dallas_mavericks).
playsfor(salah_mejri,dallas_mavericks).
playsfor(dirk_nowitzki,dallas_mavericks).
playsfor(dwight_powell,dallas_mavericks).
playsfor(deron_williams,dallas_mavericks).
playsfor(ryan_anderson,houston_rockets).
playsfor(trevor_ariza,houston_rockets).
playsfor(patrick_beverley,houston_rockets).
playsfor(corey_brewer,houston_rockets).
playsfor(bobby_brown,houston_rockets).
playsfor(clint_capela,houston_rockets).
playsfor(sam_dekker,houston_rockets).
playsfor(tyler_ennis,houston_rockets).
playsfor(eric_gordon,houston_rockets).
playsfor(james_harden,houston_rockets).
playsfor(montrezl_harrell,houston_rockets).
playsfor(kjmcdaniels,houston_rockets).
playsfor(nene,houston_rockets).
playsfor(chinanu_onuaku,houston_rockets).
playsfor(kyle_wiltjer,houston_rockets).
playsfor(tony_allen,memphis_grizzlies).
playsfor(wade_baldwin,memphis_grizzlies).
playsfor(vince_carter,memphis_grizzlies).
playsfor(mike_conley,memphis_grizzlies).
playsfor(troy_daniels,memphis_grizzlies).
playsfor(deyonta_davis,memphis_grizzlies).
playsfor(james_ennis,memphis_grizzlies).
playsfor(marc_gasol,memphis_grizzlies).
playsfor(jamychal_green,memphis_grizzlies).
playsfor(andrew_harrison,memphis_grizzlies).
playsfor(jarell_martin,memphis_grizzlies).
playsfor(chandler_parsons,memphis_grizzlies).
playsfor(zach_randolph,memphis_grizzlies).
playsfor(troy_williams,memphis_grizzlies).
playsfor(brandan_wright,memphis_grizzlies).
playsfor(alexis_ajinca,new_orleans_pelicans).
playsfor(omer_asik,new_orleans_pelicans).
playsfor(anthony_brown,new_orleans_pelicans).
playsfor(dante_cunningham,new_orleans_pelicans).
playsfor(anthony_davis,new_orleans_pelicans).
playsfor(cheick_diallo,new_orleans_pelicans).
playsfor(tyreke_evans,new_orleans_pelicans).
playsfor(tim_frazier,new_orleans_pelicans).
playsfor(langston_galloway,new_orleans_pelicans).
playsfor(buddy_hield,new_orleans_pelicans).
playsfor(solomon_hill,new_orleans_pelicans).
playsfor(jrue_holiday,new_orleans_pelicans).
playsfor(terrence_jones,new_orleans_pelicans).
playsfor(e_twaun_moore,new_orleans_pelicans).
playsfor(quincy_pondexter,new_orleans_pelicans).
playsfor(lamarcus_aldridge,san_antonio_spurs).
playsfor(kyle_anderson,san_antonio_spurs).
playsfor(davis_bertans,san_antonio_spurs).
playsfor(dewayne_dedmon,san_antonio_spurs).
playsfor(bryn_forbes,san_antonio_spurs).
playsfor(pau_gasol,san_antonio_spurs).
playsfor(manu_ginobili,san_antonio_spurs).
playsfor(danny_green,san_antonio_spurs).
playsfor(nicolas_laprovittola,san_antonio_spurs).
playsfor(david_lee,san_antonio_spurs).
playsfor(kawhi_leonard,san_antonio_spurs).
playsfor(patty_mills,san_antonio_spurs).
playsfor(dejounte_murray,san_antonio_spurs).
playsfor(tony_parker,san_antonio_spurs).
playsfor(jonathon_simmons,san_antonio_spurs).
playsfor(darrell_arthur,denver_nuggets).
playsfor(will_barton,denver_nuggets).
playsfor(malik_beasley,denver_nuggets).
playsfor(wilson_chandler,denver_nuggets).
playsfor(kenneth_faried,denver_nuggets).
playsfor(danilo_gallinari,denver_nuggets).
playsfor(alonzo_gee,denver_nuggets).
playsfor(gary_harris,denver_nuggets).
playsfor(juan_hernangomez,denver_nuggets).
playsfor(nikola_jokic,denver_nuggets).
playsfor(mike_miller,denver_nuggets).
playsfor(emmanuel_mudiay,denver_nuggets).
playsfor(jamal_murray,denver_nuggets).
playsfor(jameer_nelson,denver_nuggets).
playsfor(jusuf_nurkic,denver_nuggets).
playsfor(cole_aldrich,minnesota_timberwolves).
playsfor(nemanja_bjelica,minnesota_timberwolves).
playsfor(gorgui_dieng,minnesota_timberwolves).
playsfor(kris_dunn,minnesota_timberwolves).
playsfor(jordan_hill,minnesota_timberwolves).
playsfor(tyus_jones,minnesota_timberwolves).
playsfor(zach_laVine,minnesota_timberwolves).
playsfor(john_lucas,minnesota_timberwolves).
playsfor(shabazz_muhammad,minnesota_timberwolves).
playsfor(adreian_payne,minnesota_timberwolves).
playsfor(nikola_pekovic,minnesota_timberwolves).
playsfor(ricky_rubio,minnesota_timberwolves).
playsfor(brandon_rush,minnesota_timberwolves).
playsfor(karl-anthony_towns,minnesota_timberwolves).
playsfor(andrew_wiggins,minnesota_timberwolves).
playsfor(alex_abrines,oklahoma_city_thunder).
playsfor(steven_adams,oklahoma_city_thunder).
playsfor(semaj_christon,oklahoma_city_thunder).
playsfor(nick_collison,oklahoma_city_thunder).
playsfor(jerami_grant,oklahoma_city_thunder).
playsfor(josh_huestis,oklahoma_city_thunder).
playsfor(enes_kanter,oklahoma_city_thunder).
playsfor(joffrey_lauvergne,oklahoma_city_thunder).
playsfor(anthony_morrow,oklahoma_city_thunder).
playsfor(victor_oladipo,oklahoma_city_thunder).
playsfor(cameron_payne,oklahoma_city_thunder).
playsfor(andre_roberson,oklahoma_city_thunder).
playsfor(domantas_sabonis,oklahoma_city_thunder).
playsfor(kyle_singler,oklahoma_city_thunder).
playsfor(russell_westbrook,oklahoma_city_thunder).
playsfor(al-farouq_aminu,portland_trail_blazers).
playsfor(pat_connaughton,portland_trail_blazers).
playsfor(allen_crabbe,portland_trail_blazers).
playsfor(ed_davis,portland_trail_blazers).
playsfor(festus_ezeli,portland_trail_blazers).
playsfor(maurice_harkless,portland_trail_blazers).
playsfor(jake_layman,portland_trail_blazers).
playsfor(meyers_leonard,portland_trail_blazers).
playsfor(damian_lillard,portland_trail_blazers).
playsfor(cjmccollum,portland_trail_blazers).
playsfor(shabazz_napier,portland_trail_blazers).
playsfor(mason_plumlee,portland_trail_blazers).
playsfor(tim_quarterman,portland_trail_blazers).
playsfor(evan_turner,portland_trail_blazers).
playsfor(noah_Vonleh,portland_trail_blazers).
playsfor(joel_bolomboy,utah_jazz).
playsfor(alec_burks,utah_jazz).
playsfor(boris_diaw,utah_jazz).
playsfor(dante_exum,utah_jazz).
playsfor(derrick_favors,utah_jazz).
playsfor(rudy_gobert,utah_jazz).
playsfor(gordon_hayward,utah_jazz).
playsfor(george_hill,utah_jazz).
playsfor(rodney_hood,utah_jazz).
playsfor(joe_ingles,utah_jazz).
playsfor(joe_johnson,utah_jazz).
playsfor(trey_lyles,utah_jazz).
playsfor(shelvin_mack,utah_jazz).
playsfor(raul_neto,utah_jazz).
playsfor(jeff_withey,utah_jazz).
playsfor(ian_clark,golden_state_warriors).
playsfor(stephen_curry,golden_state_warriors).
playsfor(kevin_durant,golden_state_warriors).
playsfor(draymond_green,golden_state_warriors).
playsfor(andre_iguodala,golden_state_warriors).
playsfor(damian_jones,golden_state_warriors).
playsfor(shaun_livingston,golden_state_warriors).
playsfor(kevon_looney,golden_state_warriors).
playsfor(james_michael_mcadoo,golden_state_warriors).
playsfor(patrick_mccaw,golden_state_warriors).
playsfor(jaVale_mcgee,golden_state_warriors).
playsfor(zaza_pachulia,golden_state_warriors).
playsfor(klay_thompson,golden_state_warriors).
playsfor(anderson_Varejao,golden_state_warriors).
playsfor(david_west,golden_state_warriors).
playsfor(alan_anderson,los_angeles_clippers).
playsfor(brandon_bass,los_angeles_clippers).
playsfor(jamal_crawford,los_angeles_clippers).
playsfor(raymond_felton,los_angeles_clippers).
playsfor(blake_griffin,los_angeles_clippers).
playsfor(brice_johnson,los_angeles_clippers).
playsfor(wesley_johnson,los_angeles_clippers).
playsfor(deandre_jordan,los_angeles_clippers).
playsfor(luc_mbah_a_moute,los_angeles_clippers).
playsfor(chris_paul,los_angeles_clippers).
playsfor(paul_pierce,los_angeles_clippers).
playsfor(jjredick,los_angeles_clippers).
playsfor(austin_rivers,los_angeles_clippers).
playsfor(marreese_speights,los_angeles_clippers).
playsfor(diamond_stone,los_angeles_clippers).
playsfor(tarik_black,los_angeles_lakers).
playsfor(jose_calderon,los_angeles_lakers).
playsfor(jordan_clarkson,los_angeles_lakers).
playsfor(luol_deng,los_angeles_lakers).
playsfor(marcelo_huertas,los_angeles_lakers).
playsfor(brandon_ingram,los_angeles_lakers).
playsfor(timofey_mozgov,los_angeles_lakers).
playsfor(larry_nance,los_angeles_lakers).
playsfor(julius_randle,los_angeles_lakers).
playsfor(thomas_robinson,los_angeles_lakers).
playsfor(d_angelo_russell,los_angeles_lakers).
playsfor(lou_williams,los_angeles_lakers).
playsfor(metta_world_peace,los_angeles_lakers).
playsfor(nick_young,los_angeles_lakers).
playsfor(ivica_zubac,los_angeles_lakers).
playsfor(leandro_barbosa,phoenix_suns).
playsfor(dragan_bender,phoenix_suns).
playsfor(eric_bledsoe,phoenix_suns).
playsfor(devin_booker,phoenix_suns).
playsfor(tyson_chandler,phoenix_suns).
playsfor(marquese_chriss,phoenix_suns).
playsfor(jared_dudley,phoenix_suns).
playsfor(john_jenkins,phoenix_suns).
playsfor(derrick_jones,phoenix_suns).
playsfor(brandon_knight,phoenix_suns).
playsfor(alex_len,phoenix_suns).
playsfor(pjtucker,phoenix_suns).
playsfor(tyler_ulis,phoenix_suns).
playsfor(tj_warren,phoenix_suns).
playsfor(alan_williams,phoenix_suns).
playsfor(arron_afflalo,sacramento_kings).
playsfor(matt_barnes,sacramento_kings).
playsfor(omri_casspi,sacramento_kings).
playsfor(willie_cauley-stein,sacramento_kings).
playsfor(darren_collison,sacramento_kings).
playsfor(demarcus_cousins,sacramento_kings).
playsfor(rudy_gay,sacramento_kings).
playsfor(kosta_koufos,sacramento_kings).
playsfor(skal_labissiere,sacramento_kings).
playsfor(ty_lawson,sacramento_kings).
playsfor(ben_mclemore,sacramento_kings).
playsfor(georgios_papagiannis,sacramento_kings).
playsfor(malachi_richardson,sacramento_kings).
playsfor(garrett_temple,sacramento_kings).
playsfor(anthony_tolliver,sacramento_kings).
